// Extracted declaration from ../main-ui.js:102507-102541.
// Navigation/reference excerpt; shared bundle dependencies are NOT imported.
// Edit ../main-ui.js for a runnable change. This is not original TS/TSX source.
const DefaultServerConfiguration = {
    current_slot_index: -1,
    voice_changer_input_mode: "client",
    sio_broadcast: !1,
    pass_through: !1,
    recording_started: !1,
    enable_high_pass_filter: !1,
    high_pass_filter_cutoff: 0,
    enable_low_pass_filter: !1,
    low_pass_filter_cutoff: 0,
    volume_tuning_type: "sqrt",
    audio_input_device_index: -1,
    audio_output_device_index: -1,
    audio_monitor_device_index: -1,
    wasapi_exclude_emabled: !1,
    audio_input_device_sample_rate: 0,
    audio_output_device_sample_rate: 0,
    audio_monitor_device_sample_rate: 0,
    audio_input_device_gain: 0,
    audio_output_device_gain: 0,
    audio_monitor_device_gain: 0,
    server_device_trancate_buffer_ratio: 0,
    realtime_process_status_enabled: !1,
    realtime_process_status_send_interval_sec: 2,
    realtime_output_status_enabled: !1,
    realtime_output_status_send_interval_sec: 0.2,
    noise_gate: 0,
    extra_frame_sec: 0,
    crossfade_sec: 0,
    sola_search_frame_sec: 0,
    gpu_device_id_int: 0,
    input_sample_rate: 0,
    output_sample_rate: 0,
    monitor_sample_rate: 0,
  };
